var aNavContentData = [
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/phone6.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone6.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone6.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/phone6.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone6.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone6.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone6.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone6.jpg",
			name:"小米CC9",
			price:"1799"
		}
	]
];
var aCateContentData = [
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/phone1.jpg",
			name:"Redmi K20 Pro"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone2.jpg",
			name:"Redmi Note 7"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone1.jpg",
			name:"Redmi K20 Pro"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone2.jpg",
			name:"Redmi Note 7"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/phone1.jpg",
			name:"Redmi K20 Pro"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone2.jpg",
			name:"Redmi Note 7"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone1.jpg",
			name:"Redmi K20 Pro"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone2.jpg",
			name:"Redmi Note 7"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone1.jpg",
			name:"Redmi K20 Pro"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/phone1.jpg",
			name:"Redmi K20 Pro"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone2.jpg",
			name:"Redmi Note 7"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/phone1.jpg",
			name:"Redmi K20 Pro"
		}
	]

];
/*
	<li class="product-item product-item-m transition-box" >
		<img class="product-img" src="images/jd3.jpg" alt="">
		<p class="product-name">米家互联网空调C1 一级能效</p>
		<p class="product-desc">1.5匹/自清洁/全直流变频</p>
		<p class="product-price">
			<span>2399元</span>
			<del>2799元</del>
		</p>
		<span class="new1">新品</span>
		<div class="comment">
			<p class="comment-content">很满意，非常喜欢，开心</p>
			<p class="comment-author">来自于 <span>童童</span> 的评价</p>
		</div>
	</li>

*/
var aTabContentData = [
	[
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1第一页",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			top:{
				name:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"images/jiadian4.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"images/jiadian5.png"
			}
		}
	],
	[
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1第二页",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			top:{
				name:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"images/jiadian4.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"images/jiadian5.png"
			}
		}
	],
	[
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1第三页",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			top:{
				name:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"images/jiadian4.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"images/jiadian5.png"
			}
		}
	],
	[
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1第四页",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			img:"images/jd3.jpg",
			name:"米家互联网空调C1 一级能效",
			desc:"1.5匹/自清洁/全直流变频",
			price:"2399",
			del:"2799",
			new:{
				name:"new1",
				content:"新品"
			},
			comment:{
				content:"很满意，非常喜欢，开心",
				author:"童童"
			}
		},
		{
			top:{
				name:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"images/jiadian4.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"images/jiadian5.png"
			}
		}
	]



]